use_frameworks!

abstract_target 'AllTests' do
    pod 'MFBBinding', :path => '../'
    pod 'OCMock', :git => 'https://github.com/flix-tech/ocmock', :branch => 'custom'

    target 'MFBBindingTests'
    target 'MFBBindingTests_BlockAssertions'
end
