# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c
rvm: 2.3.0
cache: bundler
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
branches:
  only:
    - master
env:
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=8.1,name=iPhone 5" SCHEME="MFBBindingTests_Debug" #32-bit
    - DESTINATION="platform=iOS Simulator,OS=9.3,name=iPhone 5" SCHEME="MFBBindingTests_Debug" #32-bit
    - DESTINATION="platform=iOS Simulator,OS=9.3,name=iPhone 6s" SCHEME="MFBBindingTests_Debug" #64-bit
    - DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPhone 6s" SCHEME="MFBBindingTests_Debug" #64-bit

    - DESTINATION="platform=iOS Simulator,OS=8.1,name=iPhone 5" SCHEME="MFBBindingTests_Release" #32-bit
    - DESTINATION="platform=iOS Simulator,OS=9.3,name=iPhone 5" SCHEME="MFBBindingTests_Release" #32-bit
    - DESTINATION="platform=iOS Simulator,OS=9.3,name=iPhone 6s" SCHEME="MFBBindingTests_Release" #64-bit
    - DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPhone 6s" SCHEME="MFBBindingTests_Release" RUN_DANGER=1 #64-bit

script:
- set -o pipefail && travis_retry xcodebuild test -workspace Example/MFBBinding.xcworkspace -scheme "$SCHEME" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO | bundle exec xcpretty
- pod lib lint
- if [ "$RUN_DANGER" = 1 ]; then brew bundle; fi
- if [ "$RUN_DANGER" = 1 ]; then bundle exec danger; fi
