# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
env:
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=8.1,name=iPhone 5" #32-bit
    - DESTINATION="platform=iOS Simulator,OS=9.3,name=iPhone 5" #32-bit
    - DESTINATION="platform=iOS Simulator,OS=9.3,name=iPhone 6s" #64-bit

script:
- set -o pipefail && xcodebuild test -workspace Example/MFBBinding.xcworkspace -scheme MFBBindingTests -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
